### ISSUE TITLE
Trouble when using rules

### ISSUE THREAD

**Issue by WeeBeasties** [curso-r/auth0#10]
I have a shiny server instance on a DigitalOcean droplet. I'm hoping to use auth0 to regulate access to some of the shiny apps that I have on that server, but leave others open to the public (some apps relate to University-specific analytics that I might want to keep private). I have the shiny server, auth0, and your package (thanks for that, by the way) working just fine. However, strange things happen when I try to put an email whitelist rule in place. If I add a user with the whitelisted email domain, everything works as expected. However, if I add a user for a non-whitelisted domain the authentication process enters an infinite loop of failing the login and trying to load the login page again. I expected it to just go back to the login location and show an error message. Perhaps I have something wrong in the configuration... I'm pretty new to auth0, so I don't quite know how to proceed from here. Any suggestions would be appreciated.

**Comment by jtrecenti** [comment]
Hi @WeeBeasties , thanks for the interest on auth0 package.

It seems like a bug. I'll make some tests this week to reproduce and try to solve your problem. Thanks!

**Comment by jtrecenti** [comment]
Hi @WeeBeasties, could you try this branch? to install it, run

```r
devtools::install_github("curso-r/auth0", ref = "roadmap-0.1.2")
```

It has some breaking changes in userInfo and logoutButton(), so maybe you'll need to change some code of your app. Sorry for that.

The problem was that auth0 was trying to log-in the unauthorized user many times. The workaround was to run the logout url when the login comes with an error.

Please let me know if it works.

**Comment by WeeBeasties** [comment]
The installed branch solved the unauthorized user looping problem for me. I was experimenting with a logoutButton, but that isn't working correctly anymore now. When I try to use a user that fails the rule, I get sent back to the login screen now (but the failure message is not shown). I probably do not have all the configuration parameters set correctly...
