### ISSUE TITLE
Documentation: mention that the "Run App" button in RStudio cannot be used

### ISSUE THREAD

**Issue by daattali** [curso-r/auth0#15]

**Comment by jtrecenti** [comment]
Agree. And that's so sad :(

**Comment by jtrecenti** [comment]
just realized that RStudio just searches for the string `shinyApp` in the `app.R` file to add the button in the corner. There are some alternatives here:

1. add a `shinyApp` comment, like

```r
# shinyApp
library(shiny)
library(auth0)

ui <- fluidPage(logoutButton())

server <- function(input, output, session) { }
auth0App(ui, server)
```

2. change `auth0App()`'s name to something that includes `shinyApp`

- `auth0_shinyapp`
- `shinyApp0`

What do you think?

Also, when before running `runApp()` or clicking the button, the user must fix the port running `options(shiny.port = 8100)`, or other port configured in the yml file.

**Comment by daattali** [comment]
How about `shinyAppAuth0()` ? Whatever you think is best. And yes the port does need to be set as well. Lots of documentation!
