### ISSUE TITLE
Suggestion: add `auth0AppDir` function (equivalent to shinyAppDir - where you provide a directory instead of the actual ui and server objects)

### ISSUE THREAD

**Issue by daattali** [curso-r/auth0#21]

**Comment by jtrecenti** [comment]
I tried to solve this and it seems like there's no easy way. I think this is as difficult as making auth0 work seamlessly with `ui.R/server.R` framework :disappointed:

**Comment by daattali** [comment]
That's a shame. Do you think it'd be possible to have a `auth0AppDir()` function that takes a directory and simply goes there, grabs the ui and the server (by sourcing them and saving their return value), and passes that into shinyAuth0App?

**Comment by jtrecenti** [comment]
Yes, it is possible! Tomorrow I'll try this idea. It'll be different of the
original function but at least it will work. I think that the problem of
this approach will be generalizations to apps using www/ and so on

Em dom, 9 de jun de 2019 23:28, Dean Attali <notifications@github.com>
escreveu:

**Comment by daattali** [comment]
Yeah, I guess the dir's www folder should also be added as a resource path.
Of course there's other little things that would need to be tasted, it
looks like you know what to look for :)

**Comment by chintanp** [comment]
Any updates on this? I tried to use the shiny-example of [bus-dashboard](https://github.com/rstudio/shiny-examples/tree/master/086-bus-dashboard) which is a two file setup (ui.R, server.R) by copying the contents on ui.R and server.R to a file app.R and creating variables `ui` and `server` from them, but it doesnt display the elements correctly. The leaflet map is not displayed and whole dashboard is displayed twice.

**Comment by jtrecenti** [comment]
This is related to #5. `shiny::shinyAppDir()` will just work after the next pull request.
