### ISSUE TITLE
Suggestion: don't add "?code=xxx" to the URL

### ISSUE THREAD

**Issue by daattali** [curso-r/auth0#22]
I think that would present some issues sometimes, it's best to not mess with the query string and leave it as-is for the developer to not have any surprises.

I thought you already implemented this when I saw you in Rio :)

**Comment by daattali** [comment]
Just realized that one more reason to avoid this is because when I refresh a page that already has the code in the URL, then the app grays out because it tries to use an old code

**Comment by clente** [comment]
Fixed with PR #28. For now this solution will do, but I'm creating a new issue for people to report problems with this behavior.
