### ISSUE TITLE
Consistent reliable way to get unique logged in user ID?

### ISSUE THREAD

**Issue by daattali** [curso-r/auth0#23]
When looking at the login_info object is there a standard field I can always expect to have that will give me the unique name of a logged in user? It would be extremely useful if there is a single field that will be consistent regardless of what login mechanism is used, that I know will always give me back a username and that I can use it to uniquely identify a user.

**Comment by jtrecenti** [comment]
I'll create some examples to see if it's possible.

**Comment by jtrecenti** [comment]
Just found that the `login_info` (soon it'll be `auth0_info`) has a `sub` field which is unique for each user. It identifies first the provider (like `google-oauth2`) and then an unique ID (like `1234567890`) generated by Auth0 itself.

**Comment by daattali** [comment]
Great. Let me know if you verify

**Comment by daattali** [comment]
This is great! The documentation is so detailed and helpful. The only thing that IMO is still a bit unclear is the "Alternative configuration options" section - it doesn't explain what the local and remote URLs are, it only says how to set them
