### ISSUE TITLE
Suggestion: instead of passing around the config_file parameter between functions, define it once when the app initializes

### ISSUE THREAD

**Issue by daattali** [curso-r/auth0#25]
Right now, the config file path is being passed around between different functions. It would be better and less error prone to have `shinyAuth0App` save the file path that it's given (since that's the only place where the user supplies it initially) in some sort of global variable that all the other functions can then access

**Comment by jtrecenti** [comment]
I think it is already possible to set the path using `options()`, like

```
options(auth0_config_file = "path/to/_auth0.yml")
```

the function `find_config_file()` tries to get it from there. Is it enough?

**Comment by daattali** [comment]
I think it would be much cleaner to not just make it possible, but entirely
remove the option of passing it around internally everywhere. It's ok for
the user to either set it as a config option or pass it to the
`shinyAuth0App()` , but auth0 internally shouldn't be passing this variable
around everywhere - it should just define it once inside shinyAuth0App()
and always use that same value. In my opinion that's a much cleaner design

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>
