### ISSUE TITLE
Feature request: have a way to automatically get past the login screen for testing/dev purposes

### ISSUE THREAD

**Issue by daattali** [curso-r/auth0#26]
While developing a shiny app or working on auth0 features, it can be very frustrating that every time I run the app I need to click on the login button, it takes ~5 seconds per run, which quickly adds up when running the app dozens of time for quick iteration. It would be great to be able to have some flag that allows the login screen to be surpassed and do a mock login.

**Comment by jtrecenti** [comment]
A possible solution could be a new parameter to `auth0App()`.

```r
auth0::auth0App(ui, server, disable = TRUE)
```

My fear is the user forget to delete this in production. Another solution could be

```r
auth0::auth0App(ui, server, disable_local = TRUE)
```

What do you think?

**Comment by daattali** [comment]
Disable is better than diaable_local, because I don't think the package should try to guess the environment, and also sometimes you would want to disable it on a deployed app if you're trying to debug something that's deployed.

What I personally like even more is having a config option flag, that way you don't need to worry about accidentally changing it locally and forgetting to revert
