### ISSUE TITLE
Alternative to stripping URL metadata

### ISSUE THREAD

**Issue by clente** [curso-r/auth0#30]
With #28, all URL metadata is stripped. This might create problems for developers, so the ideal is to find an alternative fix to #22.

**Comment by clente** [comment]
#31 apparently fixes this.

**Comment by clente** [comment]
A new attempt to solve this comes with #38.

@daattali are you able to test whether or not this solution fits your needs?

**Comment by daattali** [comment]
I haven't tested it yet but had a few comments on the PR
