### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by ignacio82** [curso-r/auth0#32]
To reproduce this bug I have to do the following:

1. Login into my app. (everything works fine)
2. Close that tab
3. Open a new tab and login to the app again. The shiny app crashes with the following error:

```r
my-shiny-app   |   67: curl::curl_fetch_memory
my-shiny-app   |   66: request_fetch.write_memory
my-shiny-app   |   64: request_perform
my-shiny-app   |   63: POST
my-shiny-app   |   62: httr::oauth2.0_access_token
my-shiny-app   |   61: auth0_server_verify
my-shiny-app   |   48: server
my-shiny-app   | Error in curl::curl_fetch_memory(url, handle = handle) :
my-shiny-app   |   Error in the HTTP2 framing layer

```

Have you encountered this error before? I'm not sure how to debug this. Thanks for the help!

**Comment by jtrecenti** [comment]
please try again with the new version. Thanks!

**Comment by jtrecenti** [comment]
@ignacio82 did you manage to try with the new version?

**Comment by ignacio82** [comment]
Sorry, I was not able to try it. We ended up removing auth0 and are too busy to try to add it back.
