### ISSUE TITLE
Consistent way to get email id of the user

### ISSUE THREAD

**Issue by chintanp** [curso-r/auth0#35]
I am able to get the user name, sub etc from `session$userData$auth0_info` but it does not give the user's email id when the user logs in from a google account. Any suggestions on how to get it?

**Comment by jtrecenti** [comment]
Hi @chintanp, thank you for the issue. It's not possible yet in `{auth0}` package, but it is possible if you change the package source code in this line

https://github.com/curso-r/auth0/blob/master/R/auth0.R#L84

If you replace `"openid profile"` by `"openid email profile"`, you'll be able to access the user e-mail (if she/he grant the access).

This upgrade will be available when we implement Auth0's API in your package.

**Comment by jtrecenti** [comment]
More information here:

https://community.auth0.com/t/how-to-access-user-email-address/7806/2

**Comment by chintanp** [comment]
I tried reinstalling the R package after changing the code as suggested. To re-install I used remotes::install_local() from the package repo folder. And the install proceeds successfully, I still get the same values in my `auth0_info` object. Is there a suggested procedure to re-install from the source?

**Comment by jtrecenti** [comment]
It works in my computer. Maybe you need restart the session.

**Comment by chintanp** [comment]
Worked for me too. Had to remove the old version of the package and re-install again. Thanks.
