### ISSUE TITLE
auth0 and shiny modules

### ISSUE THREAD

**Issue by MooJoh** [curso-r/auth0#37]
I setup auth0 to run with the example shiny app, which works as intended.
Another shiny app, where I use shiny modules, works fine without auth0, but crashes when running with shinyAuth0App().

Login works actually fine, but when redirected to the shiny app the following error message pops up:

`Listening on http://127.0.0.1:8100
Warning: Error in as.character: cannot coerce type 'closure' to vector of type 'character'
  [No stack trace available]`

Is auth0 intended to work with shiny modules? Any experiences?
Thanks in advance, great work by the way!

**Comment by jtrecenti** [comment]
Yes, I use it with modules. Actually we're using {golem} package and their modules a lot.

Do you have a reproducible code? Thanks!

**Comment by MooJoh** [comment]
Turns out the main ui should not be defined as a function.
Thanks for your feedback @jtrecenti
