### ISSUE TITLE
Provide client access to the authorization credentials

### ISSUE THREAD

**Issue by AB-Kent** [curso-r/auth0#39]
I'm using this package to authorize access to a website which requires that the JSON Web Token returned by Auth0 is included in an Authorization header with each web request. This package currently provides access to the user info returned by Auth0 but not to the JWT.

I have a changeset which saves the returned token in `session$userData$auth0_credentials. I'll submit a pull request; it would be great to have this change incorporated here.

**Comment by jtrecenti** [comment]
Included in #b3a8896. Now we need to improve the docs #41
