### ISSUE TITLE
WISH: Make htmltools, shiny, shinyjs optional?

### ISSUE THREAD

**Issue by HenrikBengtsson** [curso-r/auth0#48]
Just discovered this nice package. It looks like the API for the Auth0 API is the essential functionality of this package and may be of value outside of the Shiny world.  Would it make sense to move several of the heavy packages under Imports to Suggests, so that they don't have to be downloaded/installed if not needed, i.e. shiny, shinyjs, and htmltools?

**Comment by jtrecenti** [comment]
Hi Henrik, I agree about the API and it is in the roadmap to version 0.3.0 of Auth0!

About dependencies: I think that the only heavy dependence is `shiny`.

`htmltools` is imported by shiny, so it is really necessary. I could change `htmltools::tags` to `shiny::tags` but I think that it won't make any practical difference. 

`shinyjs` imports digest, htmltools, jsonlite (all of which are imported by shiny), and shiny.

**Comment by HenrikBengtsson** [comment]
Curious, what would prevent all shiny parts be using `shiny::...` calls?

**Comment by jtrecenti** [comment]
Hi Henrik, thanks. I changed all `htmltools::` to `shiny::` as suggested.

**Comment by clente** [comment]
Will reopen when we find a solution
