### ISSUE TITLE
Make auth0 work on shinyapps.io

### ISSUE THREAD

**Issue by MislavSag** [curso-r/auth0#52]
I successfully implement auth0 locally, but when I deployed my shiny app on shinyapps.io it doesn'twork. It returns following message:

> Callback URL mismatch.
> The provided redirect_uri is not in the list of allowed callback URLs.
> Please go to the Application Settings page and make sure you are sending a valid callback url from your application. 

In Application settings I added following urls to callback:

> http://localhost:8080, https://forensis.shinyapps.io, http://127.0.0.1:8080

My remote url is empty:
```
name: TelefoniPlus
remote_url: ''
auth0_config:
  api_url: https://dev-...eu.auth0.com
  credentials:
    key: "Awj7N...."
    secret: "tO_Ta1RzxxP....
```
How should I change config file or Application settings in auth0 to make it work?

One bonus question. Is it possible to get role for specific user?

**Comment by jtrecenti** [comment]
You need to change the "remote_url" to "https://<user>.shinyapps.io/<appname>" and add this url to Auth0's callback URL to the “Allowed Callback URLs”, “Allowed Web Origins” and “Allowed Logout URLs”.

Just make sure that these addresses are correct. If you are placing your app inside a folder (e.g. https://johndoe.shinyapps.io/fooBar), don’t include the folder (fooBar) in “Allowed Web Origins”.

About role specific user, you can start from this example: https://curso-r.github.io/auth0/articles/examples/userinfo.html

and use this information to change the dashboard based on the user id.

**Comment by MislavSag** [comment]
I did everything as you said, but it returns an error:

> We can’t connect to the server at .shinyapps.io.

I add same url to “Allowed Logout URLs”.,  “Allowed Callback URLs”, “Allowed Web Origins” and remote url in config file:

> https://.shinyapps.io/

I also tried to add

>  https://forensis.shinyapps.io/

but didn't work.

**Comment by MislavSag** [comment]
I saw auth0 has an API, so I got all roles via API requests...

**Comment by jtrecenti** [comment]
> do I have to add options(shiny.port = 8080) at the begining of the app?

no, you only need that for local apps

> https://forensis.shinyapps.io/TelefoniPlus/

This "https://forensis.shinyapps.io/TelefoniPlus/" should be what's added in "remote_url" and "Allowed ...". 

I'm so sorry... the last message was wrongly parsed by GitHub and I didn't see it. It supressed the text when I typed `<name>`.

**Comment by MislavSag** [comment]
I have added https://forensis.shinyapps.io/TelefoniPlus/ to all fileds.

But now app behaves very odd. First, when app is deployed and open for first time it is already loged in. 

If I than click logout button it disconnected from the server and doesn't show login page at all.

**Comment by jtrecenti** [comment]
Ht Mislav, your app is running fine here, but the logout button is not working for some reason.

Please this example to check if anything is wrong in your configuration

https://rseis.shinyapps.io/logout/

Code: https://curso-r.github.io/auth0/articles/examples/logout.html

![image](https://user-images.githubusercontent.com/1425970/66429817-36f51e00-e9ef-11e9-929f-8abec2b60eb0.png)

**Comment by MislavSag** [comment]
Here is my setup:

![image](https://user-images.githubusercontent.com/33196375/66431179-ca444880-ea1b-11e9-8cbd-2191cad0c259.png)

I have also tried with https://forensis.shinyapps.io instead of https://forensis.shinyapps.io/TelefoniPlus, but without success. Now I get the same rror from the beginning.

 I have also tried to remove logoutbutton.

I will try tomorrow with you example.

**Comment by MislavSag** [comment]
I can't get it working even with your example. 

This return an error:
```

> 
> Allowed Callback URLs: http://localhost:8080,
> https://forensis.shinyapps.io/logout/
> 
> Allowed Web Origins: http://localhost:8080, 
> https://forensis.shinyapps.io
> 
> Allowed Logout URLs: http://localhost:8080, 
> https://forensis.shinyapps.io/logout/
```

This also return an error:
```

Allowed Callback URLs: http://localhost:8080,
https://forensis.shinyapps.io/TelefoniPlus/logout/

Allowed Web Origins: http://localhost:8080, 
https://forensis.shinyapps.io

Allowed Logout URLs: http://localhost:8080, 
https://forensis.shinyapps.io/TelefoniPlus/logout/
```

This works, but I am signed in when enter application and can't log out:

```
Allowed Callback URLs: http://localhost:8080,
https://forensis.shinyapps.io/TelefoniPlus

Allowed Web Origins: http://localhost:8080, 
https://forensis.shinyapps.io/TelefoniPlus

Allowed Logout URLs: http://localhost:8080, 
https://forensis.shinyapps.io/TelefoniPlus/logout
```

My config file:

```
name: 'Telefoni Plus'
remote_url: 'https://forensis.shinyapps.io/TelefoniPlus'
auth0_config:
  api_url: 'https://dev-n4dc-e-s.eu.auth0.com'
  credentials:
    key: "Awj7N...."
    secret: "tO_Ta1R...."
```
 I also tried to change remote_url to https://forensis.shinyapps.io

**Comment by MislavSag** [comment]
I seems everything work except logout button.

**Comment by jtrecenti** [comment]
For the logout button, try to replace

https://forensis.shinyapps.io/TelefoniPlus/logout

To

https://forensis.shinyapps.io/TelefoniPlus
