### ISSUE TITLE
Call back URL mismatch after deploying shiny app at shiny apps.io

### ISSUE THREAD

**Issue by mohang13** [curso-r/auth0#56]
I have added “Allowed Callback URLs”, “Allowed Web Origins” and “Allowed Logout URLs” of my shiny app address to the auth0 settings as mentioned. But I'm getting URL mismatch error every time because shinyapps.io is using random local host like http://127.0.0.1:46018, http://127.0.0.1:34704 which keeps on changing. This makes it impossible for me to define this url in auth0 setting.

**Comment by AACsempre** [comment]
Oi!
I am having the exact same issue occurring. 
I have tested with the simplest app, it runs locally but when deploy it to shinyapps.io it doesn't work and shows the "Callback URL mismatch."
The log and technical details shows what @mohang13 mentioned: shinyapps.io using random local host which keeps on changing.

Can someone tell me what I might be doing wrong? I can't even find out it is in the R code, in the Auth0 account settings or in Shinyapps.io app settings...

Obrigado!

**Comment by jtrecenti** [comment]
Hi @AACsempre, thank you for the issue

Have you added shinyapps.io to your list of allowed callbacks?

**Comment by AACsempre** [comment]
Yes, I think I tried all combination following issue #52.
But as said in this issue #56, the "Callback URL mismatch" error message from auth0 says in the Technical Details, for example: 
"unauthorized_client: Callback URL mismatch. http://localhost:43271 is not in the list of allowed callback URLs"
Every time it show a different localhost, therefore inserting my shinyapps.io app link in the list of allowed callbacks does not work.

**Comment by jtrecenti** [comment]
It works here, can't reproduce the problem, sorry :/

**Comment by jtrecenti** [comment]
Maybe you can try to ask for help some friends at the brazilian community on Telegram: t.me/rbrasiloficial. I know that some of them use {auth0} package in their shiny apps.

There's also a video here (in portuguese): https://www.youtube.com/watch?v=_qoHMePxFhY

**Comment by mohang13** [comment]
Hi @AACsempre, you can solve this problem by adding the URL of your deployed app to the remote_url: column in _auth0.yml file.

**Comment by AACsempre** [comment]
Thank you both so much for your help!
I found the problem was in the _auth0.yml file.

I was using:
```
name: ***
shiny_config:
  local_url: http://localhost:***
  remote_url: https://***.shinyapps.io/***/
```

it works with:
```
name: ***
remote_url: https://***.shinyapps.io/***/
```

For running locally, I now just disable the auth0 through:
`options(auth0_disable = TRUE) `

**Comment by um-jglad** [comment]
I'm still seeing this exact same behavior, and have tried all the suggestions here. Is deploying to shinyapps.io still supported?
