### ISSUE TITLE
User information  returns NULL

### ISSUE THREAD

**Issue by brucefeiwang** [curso-r/auth0#6]
Hi , 

I run the example on my local with Auth0 setting up .  passed the authentication. but The user information returns null    verbatimTextOutput("user_info").  Don't know how to solve this problem.

Fei

**Comment by dfalbel** [comment]
This is a bug. You may want to try to install this branch with a fix: https://github.com/curso-r/auth0/tree/userDataFix

**Comment by jtrecenti** [comment]
The branch is now merged to the master branch https://github.com/curso-r/auth0/pull/7

**Comment by brucefeiwang** [comment]
it works now. thanks.
