### ISSUE TITLE
Single callback for muliple Shiny apps

### ISSUE THREAD

**Issue by Kvit** [curso-r/auth0#63]
I have a **number of Shiny apps** running on **Shiny Server** behind  **Nginx**, each in its own **folder**.  Is there any way I can provide a **single callback** URL for all apps and let  Nginx (or some other method)  route callback to the appropriate Shiny app? Thanks!

**Comment by clente** [comment]
As far as we know, there is no way to route the callback. If there is, it's probably only configurable on Auth0 proper.
