### ISSUE TITLE
Logout not working for google-auth

### ISSUE THREAD

**Issue by brucefeiwang** [curso-r/auth0#8]
Once I login through Google,  and then logout, I still can login through google with out typing user info.  Not sure if this is a bug.  Please help.

Fei

**Comment by jtrecenti** [comment]
Using the new `logoutButton()` I cannot reproduce this problem anymore. Could you test it please?

basically you need to create an app like this:

``` r
library(shiny)
library(auth0)

ui <- fluidPage(logoutButton())

server <- function(input, output, session) { }

auth0App(ui, server)
```
