### ISSUE TITLE
Uncorrect login URL

### ISSUE THREAD

**Issue by mcanigueral** [curso-r/auth0#84]
I have tried the package with my personal auth0 account and all works perfectly. 
However, now I have to implement the app authentication with my company's auth0 account and instead of a login URL like:
`https://mytenant.eu.auth0.com/login?state=...`
I get the following (With a Not found message):
`http://127.0.0.1:8080/:///:///mytenant.eu.auth0.com/authorize?client_id=...`

The `auth0::auth0_info` object gives me the following in the `api` component:
```
$api
<oauth_endpoint>
 request:   :///mytenant.eu.auth0.com/oauth/token
 authorize: :///mytenant.eu.auth0.com/authorize
 access:    :///mytenant.eu.auth0.com/oauth/token
```

I have not found any difference between the Settings of my personal Auth0 account and the company's account, so I don't know if the problem is in the Auth0 side or in the package side. The only difference I can think of is that my company's account was created back in 2017 and mine during this past year.

Thanks in advance.

**Comment by mcanigueral** [comment]
**Solution found:** in the `_auth0.yml` configuration file, the `api_url` parameter must contain the `https://` header in the tenant url.
```
auth0_config:
  api_url: 'https://mytenant.eu.auth0.com'
```

**Comment by Emelieh21** [comment]
Thanks a lot for figuring that out! Had the same issue and this solved it :)
