### ISSUE TITLE
blank app

### ISSUE THREAD

**Issue by schmiddybd1** [curso-r/auth0#9]
thanks for making package.  i followed instructions exactly from here: https://curso-r.github.io/auth0/.  When I run app, I get blank page.  When I try to run in browser I get following message.  Can’t reach this page

Make sure the web address https://.auth0.com is correct

Any ideas on what I may be doing wrong?  thanks

**Comment by jtrecenti** [comment]
Hi, would you mind copying hete the URL that appears when you run the app? Thanks

**Comment by schmiddybd1** [comment]
https://.auth0.com/authorize?client_id=VgeTd6M5uI7EGL2pZMGgs5ZV65e8KiP5&scope=openid%20profile&redirect_uri=http%3A%2F%2Flocalhost%3A8100&response_type=code&state=llzuec3u57

**Comment by jtrecenti** [comment]
I think you should put your username between the https:// and the .auth0.com. Could you try this please?

**Comment by schmiddybd1** [comment]
is the user name just the Domain name minus the .auth().com from Auth() website?  I tried that and it took me here: http://localhost:8100/?code=C6_VQy26Ph4ZKQfd&state=ng7b65cbkd.

I also get this error message in R console: Listening on http://127.0.0.1:8100
Warning: Error in curl::curl_fetch_memory: Could not resolve host: .auth0.com
  66: curl::curl_fetch_memory
  65: request_fetch.write_memory
  63: request_perform
  62: POST
  61: httr::oauth2.0_access_token
  60: auth0_server_verify
  47: server
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Could not resolve host: .auth0.com

**Comment by jtrecenti** [comment]
@schmiddybd1 did you manage to solve your issue? Thanks.
