### ISSUE TITLE
options(auth0_disable=TRUE) doesn't work when using auth0_ui/auth0_server 

### ISSUE THREAD

**Issue by daattali** [curso-r/auth0#92]
Follow up from https://github.com/curso-r/auth0/issues/26

The solution implemented there allows us to define `options(auth0_disable = TRUE)` in order to bypass authentication while developing. I can see [in the code](https://github.com/curso-r/auth0/blob/19d90e7b533e020449b54f67b93cfedcc30303bb/R/shiny.R#L121), and from testing, that this works when using `shinyAppAuth0()`. But when an app uses `auth0_ui()`/`auth0_server()`, the option is ignored.

**Comment by williamorim** [comment]
Implemented in 7722eba.
