### ISSUE TITLE
`shinyAppAuth0` should pass `...` shiny options even if `auth0_disable` is `TRUE`

### ISSUE THREAD

**Issue by James-G-Hill** [curso-r/auth0#93]
If the user chooses to disable `auth0` with the `auth0_disable` option they should still be able to pass options to `shiny::shinyApp`; for example, to force the app to launch into the browser with the `launch.browser` option.

**Comment by James-G-Hill** [comment]
I'm happy to fix this but I don't seem to have permission to create a branch and push back to create a Pull Request.

**Comment by williamorim** [comment]
Fixed in 2850668
